import Foundation
import SwiftData

/// One body measurement data point. Values are stored canonically:
/// kilograms for mass, centimeters for lengths, percent for body fat.
@Model
final class BodyMeasurementEntry {
    var id: UUID = UUID()
    var date: Date = Date()
    /// A `BodyMetric` raw value, or "custom:<name>" for user-defined metrics.
    var metricRaw: String = BodyMetric.bodyWeight.rawValue
    var value: Double = 0
    var notes: String = ""
    /// "manual" or "healthkit".
    var source: String = "manual"
    var healthKitID: String?

    init(date: Date = Date(), metricRaw: String, value: Double, notes: String = "") {
        self.id = UUID()
        self.date = date
        self.metricRaw = metricRaw
        self.value = value
        self.notes = notes
    }

    var metricDisplayName: String { BodyMetric.displayName(for: metricRaw) }
}

/// A private progress photo. The full image and a small thumbnail are stored
/// inside the app's SwiftData store (external storage), never in the shared
/// photo library, and are excluded from any analysis.
@Model
final class ProgressPhoto {
    var id: UUID = UUID()
    var date: Date = Date()
    var angleRaw: String = PhotoAngle.front.rawValue
    var customAngleLabel: String = ""
    @Attribute(.externalStorage) var imageData: Data = Data()
    @Attribute(.externalStorage) var thumbnailData: Data?
    var bodyWeightKg: Double?
    var notes: String = ""
    var tags: [String] = []

    init(date: Date = Date(), angle: PhotoAngle, imageData: Data, thumbnailData: Data?) {
        self.id = UUID()
        self.date = date
        self.angleRaw = angle.rawValue
        self.imageData = imageData
        self.thumbnailData = thumbnailData
    }

    var angle: PhotoAngle {
        get { PhotoAngle(rawValue: angleRaw) ?? .custom }
        set { angleRaw = newValue.rawValue }
    }

    var angleDisplayName: String {
        angle == .custom && !customAngleLabel.isEmpty ? customAngleLabel : angle.displayName
    }
}

/// A cached personal record, recomputed by `PRService` whenever sessions change.
@Model
final class PersonalRecord {
    var id: UUID = UUID()
    var kindRaw: String = PRKind.heaviestWeight.rawValue
    /// Exercise name, benchmark distance label, or split name the record belongs to.
    var subject: String = ""
    /// Human-readable detail, e.g. "5 reps @ 100 kg".
    var detail: String = ""
    /// Canonical numeric value (kg, seconds, cm, count) for sorting and comparison.
    var value: Double = 0
    var date: Date = Date()
    var sessionID: UUID?
    var computedAt: Date = Date()

    init(kind: PRKind, subject: String, detail: String, value: Double, date: Date, sessionID: UUID? = nil) {
        self.id = UUID()
        self.kindRaw = kind.rawValue
        self.subject = subject
        self.detail = detail
        self.value = value
        self.date = date
        self.sessionID = sessionID
        self.computedAt = Date()
    }

    var kind: PRKind {
        get { PRKind(rawValue: kindRaw) ?? .heaviestWeight }
        set { kindRaw = newValue.rawValue }
    }
}

/// A generated insight. Regenerated by the insights engine and matched by
/// fingerprint so dismissals stick until the underlying evidence changes.
@Model
final class Insight {
    var id: UUID = UUID()
    /// Stable hash of category + subject + evidence window; used for upserts.
    var fingerprint: String = ""
    var categoryRaw: String = InsightCategory.consistency.rawValue
    var title: String = ""
    var body: String = ""
    /// Human-readable evidence lines explaining which data produced the insight.
    var evidence: [String] = []
    var generatedAt: Date = Date()
    var isDismissed: Bool = false

    init(fingerprint: String, category: InsightCategory, title: String, body: String, evidence: [String]) {
        self.id = UUID()
        self.fingerprint = fingerprint
        self.categoryRaw = category.rawValue
        self.title = title
        self.body = body
        self.evidence = evidence
        self.generatedAt = Date()
    }

    var category: InsightCategory {
        get { InsightCategory(rawValue: categoryRaw) ?? .consistency }
        set { categoryRaw = newValue.rawValue }
    }
}
